# Generated by Django 4.2 on 2023-05-16 18:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c89dd3e0-989b-4a20-badf-061e0277fa9d'),
                 editable=False, primary_key=True, serialize=False)),
                ('hashed_id', models.CharField(max_length=200)),
                ('featured', models.BooleanField(default=False, editable=True)),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(
                    auto_now_add=True, verbose_name='date published')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('de9200a6-f6e9-4bb9-9023-dd74665b130a'),
                 editable=False, primary_key=True, serialize=False)),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='pollsapp.question')),
            ],
        ),
    ]
