# Generated by Django 4.2 on 2023-05-14 13:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pollsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='id',
            field=models.UUIDField(default=uuid.UUID('963f36ea-c11f-4ae3-9fbe-b4f275374310'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.UUID('605471fc-0ace-4be4-9c7f-9e63609701a6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
