# Generated by Django 4.2 on 2023-05-16 18:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pollsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2fb060c5-1d05-44fa-bfda-6f69aeb33118'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2aec48fe-76a0-418b-9b8c-6044bbfe3b01'), editable=False, primary_key=True, serialize=False),
        ),
    ]
