# Generated by Django 4.2 on 2023-05-16 18:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pollsapp', '0002_alter_choice_id_alter_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3330f651-d887-4bb3-b6ed-f799381871f5'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1bbf7116-0a28-4ef7-8a2a-bcc7308428fe'), editable=False, primary_key=True, serialize=False),
        ),
    ]
