# Generated by Django 4.2 on 2023-05-05 07:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_question_hashed_id_alter_choice_id_alter_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='id',
            field=models.UUIDField(default=uuid.UUID('00446a1c-e0bd-4137-88b9-882c6604f839'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='hashed_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.UUID('962b0f63-30f1-4daf-a407-8ad9e7afbe21'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(),
        ),
    ]
