# Generated by Django 4.2 on 2023-05-03 09:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a52635c0-7b22-4794-a1b1-a215efd71913'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.UUID('770378fb-079b-46a7-8b06-e1c432c886e6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
