# Generated by Django 4.2 on 2023-05-04 17:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_choice_id_alter_question_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e29e9efc-121a-442a-81f3-ce41bbd0e926'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c5a48179-e375-4117-8ee4-80138d35abbc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
