# Generated by Django 4.2 on 2023-05-04 17:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_choice_id_alter_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f81301cc-5619-4ad9-8130-cb38751e5186'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.UUID('991c9a09-3580-4b85-90b2-d538a8ebdc94'), editable=False, primary_key=True, serialize=False),
        ),
    ]
