# Generated by Django 4.2 on 2023-05-05 07:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_choice_id_alter_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hashed_id',
            field=models.CharField(default=15698, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0cc3a4b3-ccbb-4b52-abe7-df0b32d09c7d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6a2c7ba9-a6b0-445a-8ee0-9e85a28ea494'), editable=False, primary_key=True, serialize=False),
        ),
    ]
