# Generated by Django 4.2 on 2023-05-05 07:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_choice_id_alter_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='id',
            field=models.UUIDField(default=uuid.UUID('312420d2-4349-47a0-9701-eced8443ffe1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.UUID('05c9952d-6e90-4b02-8b8b-7ac78b98c58d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
